server:
  port: 8060
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/libraries}
    username: ${SPRING_DATASOURCE_USERNAME:program}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibereplicaCount: 1

image:
  repository: ghcr.io/vladlen-vozhzhaev/lab4-library
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8060

ingress:
  enabled: false

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-postgresql.rsoi.svc.cluster.local:5432/libraries"
  - name: SPRING_DATASOURCE_USERNAME
    value: "program"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "test"

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8060
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8060
  initialDelaySeconds: 40
  periodSeconds: 5
  failureThreshold: 5rnate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true