replicaCount: 1

image:
  repository: ghcr.io/vladlen-vozhzhaev/lab4-reservation
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

env:
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:postgresql://postgres-postgresql.rsoi.svc.cluster.local:5432/reservations"
  - name: SPRING_DATASOURCE_USERNAME
    value: "program"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "test"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 5
  failureThreshold: 5